image:
  - Visual Studio 2017

branches:
  only:
  - master
  - develop

environment:
  global:
    CIBW_BEFORE_BUILD: "%PYTHON%\\python.exe setup.py build_c_core"
    IGRAPH_EXTRA_CONFIGURE_ARGS: "--disable-graphml"

  matrix:
    - CIBW_BUILD: "cp3?*-win32"
      CIBW_SKIP: "*27-*"
      MSYSTEM: MINGW32
      PATH: C:\Python38;C:\Python38\Scripts;C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%
      TARGET_ARCH: "x86"
      PYTHON: C:\Python38

    - CIBW_BUILD: "cp3?*-win_amd64"
      MSYSTEM: MINGW64
      PATH: C:\Python38-x64;C:\Python38-x64\Scripts;C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
      TARGET_ARCH: "x64"
      PYTHON: C:\Python38-x64

platform:
  - x64

install:
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S autoconf automake bison flex libtool mingw-w64-x86_64-libtool mingw-w64-i686-libxml2 mingw-w64-x86_64-libxml2 zip"
  - bash -lc "pacman --noconfirm -Rs git" # Must be removed in order to use Windows git
  - "%PYTHON%\\python.exe -m pip install cibuildwheel==1.3.0"

before_build:
  - git submodule update --init --recursive

for:
  - matrix:
      only:
        - MSYSTEM: MINGW32
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
      - "%PYTHON%\\python -m cibuildwheel --output-dir wheelhouse"
  - matrix:
      only:
        - MSYSTEM: MINGW64
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
      - "%PYTHON%\\python -m cibuildwheel --output-dir wheelhouse"

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels